env:
  global:
  - AWS_REGION=ap-southeast-1
  # AWS Credentials
  - secure: h1CyU33ZPSpMYbt+UkjHFbn5ONZh0mYdxhH1ZMDMU/1PJdxUTR37Zgq70VoSOKi2vvivDqNVlsZyG43KH+1BOxDR5iGein4KwqRLAeVo3WaILVZ5Wn/VK7Kk5IeBN+yyjEuT/Mz4H601ZXJREKOXU+NjiAupocR343xKyMjh5EfqM2C42/7aujDIY4Fa3kzgdWgwA2RghgjaL98uCR3PfP4eIb4Bw4oX8nnhTXGxSzjv8GJx375hemj33DvezFBe2WQ5+hZpBC5U2/XC8o3ADu1IKwn1s2hvlkMiqWQnl0jl5svmWG5FFC7iZwr+gn4OY7OVD3SWv5USFVdn698nkjIaB9SQBYp8kc2okL5ImvsTsMhTR31dzxCNkFV1o6YT4i1OqKPf9FiR4c+9tBaDi7EpkDyr7vJHnazXb3dOlerCoKXLNxS1P8RFIyVGK70e1C3yXFN5wKs9aBGBqAhyMHYOIMBv4lcdWh4bGRCSM4Kt5zinf0l+GDYxSz0xpkS8jKFsx0DnNn5khVFvhUmMkgJu67A17UCOEP1uNXWf1nDPd6pFQ+mnHrU/G6Z/b9l5vlWaLWNQwM5bFYwB8K/eSaGi0VnvVVWmTTATIKdyHHMwwEXwxt+TB0xxKs4MBeJtPhA2YdE3oANnlfjeEQ+/qxCnE7TV1Doezqdiu8oC6p4=
  # Docker Credentials
  - secure: QZGtwDg6Vs2CTtKwZp7rMu2REYST4BkthglEkFoXkZYsZ64NrVOvzT7Vr8y6ldDqPNGOsM1r0z7rxycolPcgslGXyj5VKPyHD6ggnMnyFSF54HcMyhyEriEp3aCCddnxmea4srRrLWlM1u78XeWOa2ENhYbrdmXko6J/OV6/sdlrGlOm9mJ2JO+YRU5SEuEwdfd9LgF95myRibUbYHZPQdpFbSdtAMzFep02ntQ0gNSUl4mQmAkhr0hbuZ4Ex+tRg294N74wXIZg3/G8b5Qa5ZRzCL712aUx/JO/LzqYGYPhqB0V7l3sM/Bxb3PZ2TKHZk5gykvSJX2a+BpEWyScPwVA54gkWUyVVID4sK0UgdUylJ5ztgQoDSJ4YOT3CZcc/DXJFttrmrTrGEkLbnSl3pzmC0isC3M8GMk63NCZmrO4XVhIrwuJzDrmQuBclmf4K3HxrBYR4vh072KMoomxHicbo7x0R5qwA7UGCc+TPeCayyLvgw8mHAwuQjLEe7NX14ipspsKUcJealL3Ws1Pre9Dw6BYs53/D9FLRDKNQSaYIFg4MLXBzY1IjPGnqJi35U2B/YtFabAiWorTCShNWlsDt/cKjYHdB76SLCh1qeNT0uBQyBhCiKNQCNg8Z0l9g+oqFwT6jAfPo13sZ5e7WI3oyAJSOoMBrWY1VfC5xy4=
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install:
- docker build -t pincambodia/somleng-freeswitch .
script:
- docker run --rm pincambodia/somleng-freeswitch /usr/bin/freeswitch -version
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t pincambodia/somleng-freeswitch:$TRAVIS_BRANCH "https://github.com/$TRAVIS_REPO_SLUG.git#$TRAVIS_BRANCH"
- docker push pincambodia/somleng-freeswitch
- provider: elasticbeanstalk
  region: ap-southeast-1
  app: freeswitch
  env: freeswitch-simulator-webserver
  bucket_name: deploy.ews1294.info
  on:
    branch: simulator
