env:
  global:
    - AWS_REGION=ap-southeast-1
    - secure: "2viSsEQXyQo3IxD85nS9Q/Ep2WQ4GflEJkE9UajfWbFtSB9/5i3SgbtG1BtqGi6reQ0u9L7Bkwz6IjHRXhzliD3h57KPSnspjs44nCX6qzCVonF7qJvThs4r8pd64nbSPjchObqUsuKe49iHcBkRCLeIOiWiwuK6t+ypojA+1ZbSo3XdhUaXBMQvQlxNbyeWOi3ZTnk/Il311J+vYX2b6axvvCCfLCVCSeKiUsv6Xu0BjAZLpWzETaYVIFGrDq/09z2gIpMBmRmTDk5GKDlWfN2B6hGdswMnzMxCbrXvlzHSyxNIKqTld2XoainuWG9uMGHCZ1LiF8wmmQiVFJTJfnpLouHwGL5v2oIBh20LGFJiZOdcAqXNnY2W5bSAu46/MuWKtT/DuxaiJRYXVShG3vrIcwTk++SBNEkSkNVX5r3ZgVBdgP/LOffdvVNukaAkEusvO6xxyhoqm+Q90GI4TeyH9JjL8Jxw5/fezXNhnSLxFmgiL+FaRPAxYSKKjdKnjOHiUkPL/OFv0yE0msldjW98nw6EcWQIHXLWamJpSFaC2/FCkJJOEDy0Mmpf1HMVMighMADJZzOZITzEVacB+p3yCegpR226SbDzROi2dHTBQ9CiMhdNqC6fFStCRUCmHirgdEx5BSWYf1FCKKsQ+/TN0sWGlSKoFs1uW0RlyvI="
language: generic
deploy:
- provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: freeswitch
  env: freeswitch-production
  bucket_name: deploy.ews1294.info
  on:
    repo: somleng/freeswitch-config
    branch: somleng.ews1294.info
