language: generic
deploy:
- provider: elasticbeanstalk
  edge: true
  access-key-id:
    secure: "kmeK1hb/1fS7XG6p7XkSlHpLSVkypxi93jddPPSNWfvwBEUJDsQbGv15KdNZDgVIBnFQQkUvlSHBqToJTcpU11FGLmvRr65L93K2EN+EWq3EDKBhTzNJtD0VHIEbJiRj3VoJ+FGQzFX3Noxbsm1Tqp32k/A7/TlxYWHpIfXre/YnON2rAFyeI8pd6YRczVrRyrC2v1SapwQ31Il3Wqquxm0O6iAxhFbOR9uH+wT+O/fXtL1HMjD9KGPP0dUYD9v8jx5QDfxbaG8A/dv1HRs8VnCVGglOMEZEwKfeGxNOMCw5C7uhLiB84KHZUlbyOpdMtYO+oxlBKmNsP2JusPg5GdeVKLBVQxnRB8wvamxP0sa+mO4++JKvC1syWMlD7eAy3CG8mqOb90PMYW7FS2JRb7/+AsrqsxkXIC/8mXsBiWmd3GhHMbhM47q1fD2FQUsPeJX7uhp/BU1qS1eD5TCpREK4kqKfLdQOTciI3r/ZugXkmhMYEPIkAz687z92pWxoIBt05tS3YGVCno3JUgi+KOiMvGQF/KlGhnwucNRKRYp6vhh+FkuFOwjhrSirx8AXU8vA18/TUR9YFXYKaaLNWi86yJOFOSJoy7hpe0s80KgqINXHv1KcPx9d7sMsgpkEGlyjKT9X9XlN7SJqvW66kyY/1mDfygjvheAFSbIiG1s="
  secret-access-key:
    secure: "awFcqCN1EbGUUBOQXyr1f/HNn5t/n1HZFjqy/t2CNuxkVth+s3x2dyyPW7E9AlX5VJ0CsU3ZRsW95VeWrZAfXGgWS7+atok2c4/5/uD1n7bOlckHN8+4NtR8+kryDmyBo58pGPTkg2c3sXGhXcjiDLez3A5I16LfXohB5ytIW16D4/yMWeb7nAN5DEWmcjysPvOY9AsIlWOz9ufNJaSnsNvwMhPJWoQ9+5APYei19yc84R9YiJv/Fp48U3kp1LLut4ucLpKdyc5/NGdz2aBYX76rRLirfKfS8mLUVEHFXoypM5yKiEi942kgYtHYvjO0dyFPskMY/vAnliVIbaz/dwuIBkd6Xazl6JLaXWub9LP5hwCys+fB5t/YnZAXIOnDzBRRQECKG0G8wDXQ8KNuccBPzxK9yNMsmVZrNWuj1MxCFjv++rwnmXg4iJlS7o0O4ouBdQl9KiSxpnPdYNsz9XazsVusO/PoihinhABU0olIdp5dPcPrCb+igbeD7e1IkNQkFI3/YKMTrC2bYk1kTT97WZ+ZEPDORMw4weGGOab7KJjWo07MfmoIsWUgqQOfv/I8VPfAxuc6G8fJa+D2u6xImIwhfr2b0aGyhA1MNov8dgyOFIKQgdTuzp+KXsU9OoyvLmqEv79XEmZYkG0ScKAOzjBR+Mg9E+JPIUpOmTc="
  region: ap-southeast-1
  app: freeswitch
  env: freeswitch-production
  bucket_name: deploy.ews1294.info
  on:
    repo: somleng/freeswitch-config
    branch: somleng.ews1294.info
