services:
  - docker

env:
  global:
    - AWS_REGION=ap-southeast-1
    - secure: "TQ5IZDS866rYidiDt45/rVS8zQ9OllrJkQVva2DXbMgy+uvOmg82FrnFZcFtGyQ1IfEqt7V+O+PWlv3C0ZOdeoZf2V8qwKIXDR2vuScJ9oR5Rio0/2/sHvNbF0D3gTrmtzjCDrHeTSsHh1blHpz19XWX/dVer9tltHF07R0w2KGKHhnQ5HLQHqCweYDLUyM8lC2VaFLJxILox9fZpe95I3pn2sk+8NDvq4r4zqsa+AjIRNhSrbGahcZ5gYaNB9kZMOm1+EVadNB0P9lm98Hhkin2im4+1UMyWebPFiHk42Mt0Uxt5wc9q7SqoFHOmB8nV91NcJiVX4mhKSyJ3UEMLq21AH/+tek8Lj/Q0U5Kdx1pUof+RtMKiLGlyQrbBBNLczR0x6GWSyWDtZ0nAf4PLiXQZgLG7/aKJz803JozVPtKaN7oVSPajkrO2gi23YPE1gckdkCJleQi+4c0mhPa8rNyuvX1p8EG7jWD8HX9TJUGKGkiTyARJqygFoGiXvoc1K52bJAmMIAfgnEoqoKhci0U+VOZh4ClS/IjyNV4DRP5r9lJeqjihzxxwX9ZTSXHycaTeb4/GU8+UdNgR2Nr+bBAY6zUa5B/ghxpmjymlYReSPfWzkUhdaBcLe7Tm82RifHvYKP5RQ6gl/TWGRkRaFnzZEEC1xUbMxbBvXRLeOE="

before_install:
  - docker build -t somleng/somleng-freeswitch .

script:
  - docker run --rm somleng/somleng-freeswitch /usr/bin/freeswitch -version

deploy:
  - provider: elasticbeanstalk
    region: ap-southeast-1
    app: somleng-freeswitch
    env: somleng-freeswitch-webserver
    bucket_name: deploy.unicef.io
    on:
      repo: somleng/freeswitch-config
      branch: somleng.unicef.io
