services:
  - docker

env:
  global:
    - AWS_REGION=ap-southeast-1
    - secure: "BuZBR4ylHQ8kwKyyKwGeXogs/a5C8dSkZV6z/5rzFTMgNa/ckGf2WghcZ8mIlW1gBJhoKcERm5vrEaHAWppLF3xc3oTMziZOc59fhC6ftyFqgKNfzU2LnpGmsI9h2cx6VASh0HoyHcUtlWGGDMwzbsDB2cFZ2eFvZdyPFaIMpxMcHONIZiS5BtLidcKu+WznnQSL4EIYuqEc32Y9NUlWYIoTNOWNcxL86TihCdkAYkpFwTZNgYY+3gswy0NTqkBEpLaTeZs2XVzehm1bToAKT8qjkymkTEa/MD+F1EM1+JBEQPKYX84OZyUwyhlm92wYYcBr7GEX13bNc/0/z8+sYDS8oqqqGHlpYvfX0AHrzdbp5FimQkXeiHFX+xUhtw6V+8bEbypZNVzB2bzwhaU25ONnXPZyzy6dTBJX7sPQAbtpjJ7O0e5IUWZA4Ycwo0fX66FOi6WTNtxf5aZeQwyBjGKGEo4z9Z/KCOWi7UfdCR4D/ZiR9PgwM8FQ5u4N4GKO/s+K5x9alPwBZh9+LfVj9t99Tmdzg8Y3719qPp+VJEDq57mukyL6mFrRHZjA7Rt208YTA726lQtqaoocAG6HlD0N5Pu7DagKBfOqbCr0H//kshHGGvtpJf8dZJ7bn8r4PGtB4rQ1t3sxM/yywhBBWzVB14vHoZd1bkRIgJpywyU="

before_install:
  - docker build -t somleng/somleng-freeswitch .

script:
  - docker run --rm somleng/somleng-freeswitch /usr/bin/freeswitch -version

deploy:
  - provider: elasticbeanstalk
    region: ap-southeast-1
    app: somleng-freeswitch
    env: somleng-freeswitch-webserver
    bucket_name: deploy.unicef.io
    on:
      repo: somleng/freeswitch-config
      branch: somleng.unicef.io
