language: generic
deploy:
- provider: elasticbeanstalk
  edge: true
  access-key-id:
    secure: "0jD4PTTb8ioGm3M4UhixbttYJcg3MmeXDjOVYp9dRxkh4J2g+blWCPeX1LKqPAE1GTEZCZ9LgwH7jSXa7TC8IPey5xkpm3OwS83J/I8+zPudDR+TQRgZKN+q/fvJ1npIzkTrOuPtMbaWwEcRLhvtaLPNLdjvZNyGSQOM+VzMMGRzMQS/vQpaL+a+K5EzVTrwhczWPFGIdXFovsQ6e2L8y5zBpCO5l2loNTYYkEvsIGQN8KBMrIOIjRnigTzGhFpW+W2vANuvc2g2a2HXuqQTYrjO4tosSE48kyAMP7XEi/4zzoBIW/hfFrjHuaiEW2wm7b1bxk0WCScNZVyhZ6u0VBrStP6++T9Qy8jcY0ECgFR7QlKGbkYD0TkNMYZrsYgdRNUOsjmld0PkL2ZcohifsZeQAlZkCxOmDCF/5rbnrQh+6pVeoZyqbsGL3ZJzICWX3i4XooFqAMrrgEGciyu3QCsQbgKtw0DGfnQQf9rrblba4/bCmhJFzR49u+kNOnSf7EwGcph64zfKPXxJD/UYkobBSScBWzT8/ga4k4DVYU3M4lx/x7uJj+nm6hGvB09PaOz6Ix3QcCzwT4NzAWQMKmWzcBVmIAJFIoFYRyP/7sb43C2bZpj/lQRvyNM1ENURqwl1Z13KdIJjNjb4vMF46Jj6N5vRnV4J6laycMvYLZM="
  secret-access-key:
    secure: "gt2hAjWXrqcZGud7pFF4oGV8nH+VOrRcz3J6eDBGkIMc+hsbPwYs23622mXDjZd+Ww9xiyOX4e1Vf4Hu6DeDkAOssrcDeB4wWFDjpIZ66frb2kKMkp8Y0gh8Tp0tmMtyB5CXkBMASa8PYVEIEFGyPDMGfQx9ep5EgWw27BSxAtv1RTkAJFNv9yKvpiBshdqSPeUcTKqrxyH036/WOK4Y6A6O5QjJux+6vpSEFOOVjOJSBynKo7NT8b7woGMXteZxnh6teM5wBFiD8D+fn4B23NPdU1Hot085VP7dK+tSUr8vsu5RkxgKyOYKDaXgfL132kZhxpevoIveGFOc4rFL2ZV4Hi4iFQMQEC+4c8r9gpoZfby2Ux4hWvibTUDDatOvcIu4ccBjnt8tHxdA8DUc6hItg1mry3KSF1a+QVA8+4b2X7/eY+vSTZgGES56RJRdq6wOMReXgKEA4nzZ8F/9MEeUV+AC5uOd4dCU5dLDjY8FNWFvVMAd/I2j0+EQ1AzffAL4i7IscmhYcUgxRGkiMrug38OARRTVH1tBUsvb2r+JhorPC9X8DSDKDXecnz7cVk9y5i60UH24nNplQkl4CiJfZszG43Jq9XVuoDNhFjn3LfdNAjA3YhmR/IcXFKPhabqT3upiOaPGG9q1vXWIcjcmV630gc854adYF8b8n7c="
  region: ap-southeast-1
  app: freeswitch
  env: freeswitch
  bucket_name: somlengci
  on:
    repo: dwilkie/freeswitch-config
    branch: app.somleng.org
