env:
  global:
    - AWS_REGION=ap-southeast-1
    - secure: "ukpSL8FDp9wWJOgC5A9p/xGSAUaU5dTWF2gRLyofu/wyYEDbFs9huF+fyBMz73IidmCHj68A1bhoG5qu9etcPm/tJ/aJ5mqlGAkB9hglU1Ows4TWv23Tfm9gaCuwui+RWbXflu3eriSWRqSFLTLHkw3DdwfhjF4Gnkg1Y+0Z3WNb4pCY3kdw4IP0tNBZCTVYawcCCynFCI9kgOvaf/Kep1A2UmucevjTYqiWsrihlSXcu7Ft8q3m6RGOlpgHZ0HI/6WgxF9fz9Ggwr0RYhrl1EdXh4TZ40rLWay2Cgg1kw6isLNzZTDp4aPovh7rF2Axi0874fNJvdfAlOtXajdTEaxVZ7HW0MIVnnPPh7tQ2CofxW2OJ4nRSQC+znarFJp0fhXOF9uqjU7pjy1bB1v/AteOkmphVhoVSBnDuL8EbHBvG/ojos4l4H2SXJ7Z3xGxx7hZs7SJ5b9o5C/+DFbz1UTaYZRiVwYdkPoAV0+4Mo8tiS/mPJZtth41EUzq+qyQyGoXXtHG/SGOoPkChc2xtzqeY2tYhG9uoRuRxEsKW7OM6NUuZ6vzyH2J4EFMv8fxfkKOKuf0KHBNqrMj0rQXLW6AiL+fkMKNuA+3tggtHO1iF/YevdVHK0gnhgD0c5EpsWG8EvlOxluuYV/QGu1B620w9qZ0bhPmYqaiR9gQZB4="
language: generic
deploy:
- provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: freeswitch
  env: freeswitch-production
  bucket_name: deploy.ews1294.info
  on:
    repo: somleng/freeswitch-config
    branch: somleng.ews1294.info
