language: generic
deploy:
- provider: elasticbeanstalk
  edge: true
  access-key-id:
    secure: "S6nzEUUdI1weKCvG2YxzIZmiloTYnPqdd0NwVjh5HujF0y+Q+JRBdEmrsi8kME2cFYE3Es54PuyR0bT9FMXaK2ZgINb5J/UaTOAsAE92V9JPO3v2OpiH6i4KJtVBOc5kwMg/LZlmZnGRzc79LJews4gLmjfp2KVtldMrLoIlG58yjugAF58yVrNaMeuZTCvQmF/Snfcn98WoKCxrTB7GB+VbKQK0kSwoUSuoZgsQ6SFXJJYLsNT/3tau+Whbn5HN46rqTTGgReeQpWXzlViz37IEDyCM+hC9EW4QC6f9+HhrQSuPkETMica8Ryc7nyOVvIr3Fd3WqLI74kmt1XvcHqvPo/5G2SjE3HQvSDpLllXvocOR+OSi4jSjWKSpppqFFXZtggpU5WBcOSFqPjtAPJToYLozn1sibOGW/fVkXlYoB+WCKS5L2q2bevz73AF66kK4O1CHd0JDOSKi7deKbIUXQrpdJ5TT2cAWVrUy5/LanZSOzqa+x45k6bmSZ+Fk7iisRlR0VH3Mz6lqo+2LBhIiN3xJ8DQEYsqgXfqJCH0sNuLX3hc5TSIMENh+DY3Ze0BLVSzRdkRvk8eXtSe8ur6DriqfjO6YcY8ImS+nm61Vpoz31iTtBoEHTNJrq9S1Am+/ZEVxa8YCKQUWPbRtBB3aAcem2ahn7HYAh1yaGZM="
  secret-access-key:
    secure: "aYMfu6cFCBVbx1smivFmPsFTuQl0iAARLRQrnAVmY8mRm7I9rzqVFPZdRZc+3Leiitswe1kqr888cTi29BKozU/Nw7H7n8V7CM9RqaTTDFtyuoZJpfC6ipGO59XneLL+rhRDUcZ62wgEA0GRc+xx3EuZ4fnmcAEFgBYzGZADUedImZl+W/u6IdpaONVDKjeamFviXn7nQO6XR8D3rxq6DMValWOrgvXYPJZsOLgRzBXNG3hqdtB8OObABiNvMw3P6i9mehV8vxH+ddKAc4Ep0XVuCbpCocEv5fAq6pQMTJ3O5G4xTWsMozZ2aELjmpbB7rT0i+95NixT56ZCeKEuYJAbO/3o6O5v/x5w+WKx0a04AF6/3lVa4m9+auYiYYKaee0+jayv1Av/d6B/LkDuDhXEooJ8d+SLOgDJapyVOSUX2c1jVKp/qUyNwpUfVgzlD5y3310fSJ656F3KIKYK3MF+lwQSsMiiFuaB+l2Y1UZ96xRHQkrBRgRBM3o8gFKhV2H1pBEYecZ+u3zXYQ8xWclhB0b95cg1CnZuvYfuHvhmyLvWaWAvqu5vMswm8ynA95deZlSkpO8P9lwTfSXFqc/xaOgfXfUiUBhhAD6vfvDBV64As5Mhg9r/3kAcsUf89jpqr/3KiyucVt7G56ZpdX0CK+PVACLnQHwq85zmL40="
  region: ap-southeast-1
  app: freeswitch
  env: freeswitch-production
  bucket_name: pin-somlengci
  on:
    repo: somleng/freeswitch-config
    branch: somleng.ews1294.info
