env:
  global:
  - AWS_REGION=ap-southeast-1
  # AWS credentials
  - secure: ib86vuGoIg8nibX7fQCDLQr6o5worWOwr7ng874nOKWVnVJ7eqVwy75EMdzFr4GkbDX3apCP77W7Ngq+2/Ivdr2pBmaDoATTMt6d+EOWhvyJkDDAT2XUUkUjUEdB+/AIh0V5mEQAbu3mUQAwuiJjlKeNd58hOeHZKrwL3hDG7/P0cqfZrkkH4gIlj3Um7rFM6JywgCHqdqJuqzU80e9EJcDVlhDM7ty5URe7nc3P1FDEZAhosm6NKch7xX1r1coOqi9TtNRzuVGEkRpprIfxyQhZfSs1aNf8OmJCQgIkvD0zGZ+HcBIHcMQ1UywG8AJRrn77SODUK8dVt+65xKdJV84y2vxADMyn7di2/CO8EfC58HwsqQDJlUGjc3jLBck9O7R+a+R42+BUS6sYpE7nwl4IR/gra1f8j77/wiT7b+2Lg8BFDOJAgi5w6EvxdVQ7Lt2ZTWh9D+TKlhdSTAEepkXWzcrGWunsuFwf864DmOlIDC3DJA0GojiL2dxqXt4iT6KUH7rqcqpY+4B7me1gqEUm1+7wj3ytsj1GP2rpikyegf5z3OqniuEvxS1zOTXoclzxVkaaYMY0hsaG6zaD3I+CAmBtO1PW4EOWEKMNqD4ILFa87WK5Mo8N9auCv9R2FZ2SOAPzi0GlZlwAIuhRdiHX50ACgwTJHHbpcAyRxeQ=
  # Docker credentials
  - secure: kxBx1XRCfH/y4si1dHBYY9OSo0d64bqathvlDxjCs9i7xApiHnnN/6rUEsF62R7bzatX/1majPPEEkbCeFsp1McXMwqmPEYxCB5n9NJ6yIe9OcYavRow3Jgsp7ZUPTnz8Ph1+uY08bjWQ7hvcKti9CWZQrcu2JKaZzV0wOi18QrQ1oHjtAFCjl9unlbnZd0LE2ImdCSVrxejYHdiMOwOuH75AltshKhmHwJp7rjI00JXWC8OJsLDy96ZkXRK1p3sG9mghca1t3tjYPQYzc8GjX+Xo+SwlXicO6GSyrJDUn8s/acQVnLE24pGmIcUmfOqHb5K4DMnxOUvvz4gr9n/ZnTw0KllFF9EdqxzhPRI4BV6VuTAddMOkaD2m/6tVPBc/IDIrKo31hpIMlpK1iFijk+eZEtCRdviTc8LDi/7WcVxd1H1Q9dL/kBBIrgZjqcbHAl9JYnxl2mAZgg6Pq9exyFwPlS0Xv5thKLqcElRqkdfocRGqH3FVqio/pb3AroTCaTAYm0PyRcNJWrCD7O1QLNP3k6J7LYuRKOWu9qKPx58hwGqHSwpxn4RYgUomBSo9/tdVOItUGzGyJxTX/WxqFJ11smfK6eq5G3I4x7cquUo9G9tXAI5wOIcm/enD8IkfOIXdCcNF9Lcv8d1nQZ+6gIuPGuf2YB7a9neJXDou4w=
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install:
- docker build -t pincambodia/somleng-freeswitch .
script:
- docker run --rm pincambodia/somleng-freeswitch /usr/bin/freeswitch -version
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t pincambodia/somleng-freeswitch:latest "https://github.com/$TRAVIS_REPO_SLUG.git#$TRAVIS_BRANCH"
- docker push pincambodia/somleng-freeswitch
deploy:
- provider: elasticbeanstalk
  region: ap-southeast-1
  app: freeswitch
  env: freeswitch-production
  bucket_name: deploy.ews1294.info
  on:
    repo: PIN-Cambodia/remove-me-to-deploy
    branch: master
